"""empty message

Revision ID: cd80e9430b31
Revises: 474318c02bc6
Create Date: 2021-12-02 13:10:07.797112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd80e9430b31'
down_revision = '474318c02bc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'address', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('company', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'company', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_column('company', 'user_id')
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.drop_column('address', 'user_id')
    # ### end Alembic commands ###
